name: 'tests Linux'

on:
  push:
    branches:
      - 'master'
  pull_request:
  schedule:
      - cron: "0 0 * * 6"  # Run every Saturday at midnight

jobs:
  linux-static:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt -y update
        sudo apt -y install meson ninja-build
        sudo apt -y install libsdl2-dev
        sudo apt -y install libavcodec-dev libavutil-dev libavformat-dev libavdevice-dev libavfilter-dev libswscale-dev libswresample-dev libpostproc-dev

    - name: Run tests
      run: |
        meson setup --buildtype release builddir --default-library static
        meson test -C builddir -v

    - name: Upload Logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: linux-static-logs
        path: builddir/meson-logs

  linux-shared:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt -y update
        sudo apt -y install meson ninja-build
        sudo apt -y install libsdl2-dev
        sudo apt -y install libavcodec-dev libavutil-dev libavformat-dev libavdevice-dev libavfilter-dev libswscale-dev libswresample-dev libpostproc-dev

    - name: Run tests
      run: |
        meson setup --buildtype release builddir --default-library shared
        meson test -C builddir -v

    - name: Upload Logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: linux-shared-logs
        path: builddir/meson-logs

  valgrind:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt -y update
        sudo apt -y install meson ninja-build
        sudo apt -y install libsdl2-dev
        sudo apt -y install libavcodec-dev libavutil-dev libavformat-dev libavdevice-dev libavfilter-dev libswscale-dev libswresample-dev libpostproc-dev
        sudo apt -y install valgrind

    - name: Run memory tests
      run: |
        meson setup --buildtype debugoptimized builddir
        meson test --wrapper "valgrind --error-exitcode=1" -C builddir -v
